remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme

title: Zhao Qi from HK PolyU

description: "Zhao Qi (PolyU BME). Research WFS & DL"

logo: 

show_downloads: False

google_analytics:
