theme: jekyll-theme-minimal

title: Zhao Qi from HK PolyU

description: |
  Hello, I am Zhao Qi from Department of Biomedical Engineering, Hong Kong Polytechnic University.
  My research interests include wavefront shaping & artificial intelligence.

logo: 

show_downloads: False

google_analytics:
