theme: jekyll-theme-minimal

title: Frank from HK PolyU

description: Hello, I am Frank from HK PolyU BME. My research interests include wavefront shaping & artificial intelligence.

logo: 

show_downloads: False

google_analytics:
