remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme

title: Zhao Qi

description: "Zhao Qi - a PhD graduate from The Hong Kong Polytechnic University"

logo: 

show_downloads: False

google_analytics:
